compressionLevel: mixed

enableGlobalCache: false

injectEnvironmentFiles:
  - .env?

nodeLinker: node-modules

npmPublishAccess: public

npmScopes:
  lukso:
    npmAlwaysAuth: true
    npmAuthToken: '${LUKSO_NPM_TOKEN}'
    npmRegistryServer: 'https://registry.npmjs.com'
    npmPublishRegistry: 'https://registry.npmjs.com'

yarnPath: .yarn/releases/yarn-4.12.0.cjs
