#!/usr/bin/env node
/**
 * Generate all style files before build
 *
 * This script generates:
 * 1. colors.scss - Tailwind v3 color variables with :root
 * 2. colors-v4.css - Tailwind v4 color variables with @theme and --color- prefix
 * 3. fonts-v4.css - Font faces for Tailwind v4
 * 4. main-v4.css - Complete CSS for components (inlines colors and fonts)
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  colorPalette,
  boxShadows,
} from '../src/shared/tools/tailwind-config.js'

const __dirname = dirname(fileURLToPath(import.meta.url))
const rootDir = dirname(__dirname)
const generatedStylesDir = join(rootDir, 'src/shared/styles/generated')
const srcStylesDir = join(rootDir, 'src/shared/styles')

// Ensure generated directory exists
import { mkdirSync } from 'node:fs'
mkdirSync(generatedStylesDir, { recursive: true })

console.log('Generating style files...')

// 1. Generate colors.scss for Tailwind v3 (SCSS compatibility)
const scssPath = join(generatedStylesDir, 'colors.scss')
const scssOutput = [
  '// DO NOT MODIFY MANUALLY. This file is auto generated by scripts/generate-styles.js',
  ':root {',
]

for (const [group, colorValues] of Object.entries(colorPalette)) {
  for (const [color, value] of Object.entries(colorValues)) {
    scssOutput.push(`  --${group}-${color}: ${value};`)
  }
}
scssOutput.push('}', '')

writeFileSync(scssPath, scssOutput.join('\n'))
console.log('✓ Generated colors.scss')

// 2. Generate colors.css for Tailwind v3 (CSS format)
const cssV3Path = join(generatedStylesDir, 'colors.css')
const cssV3Output = [
  '/* DO NOT MODIFY MANUALLY. This file is auto generated by scripts/generate-styles.js */',
  ':root {',
]

for (const [group, colorValues] of Object.entries(colorPalette)) {
  for (const [color, value] of Object.entries(colorValues)) {
    cssV3Output.push(`  --${group}-${color}: ${value};`)
  }
}
cssV3Output.push('}', '')

writeFileSync(cssV3Path, cssV3Output.join('\n'))
console.log('✓ Generated colors.css')

// 3. Generate colors-v4.css for Tailwind v4 (with --color- prefix)
const cssPath = join(generatedStylesDir, 'colors-v4.css')
const cssOutput = [
  '/* DO NOT MODIFY MANUALLY. This file is auto generated by scripts/generate-styles.js */',
  '@theme {',
]

for (const [group, colorValues] of Object.entries(colorPalette)) {
  for (const [color, value] of Object.entries(colorValues)) {
    // Tailwind v4 requires color-* prefix for bg-*, text-*, border-* utilities
    cssOutput.push(`  --color-${group}-${color}: ${value};`)
  }
}
cssOutput.push('}', '')

writeFileSync(cssPath, cssOutput.join('\n'))
console.log('✓ Generated colors-v4.css')

// 4. Generate fonts-v4.css
const fontsPath = join(generatedStylesDir, 'fonts-v4.css')
const fontsCss = `/* DO NOT MODIFY MANUALLY. This file is auto generated by scripts/generate-styles.js */
@font-face {
  font-family: Inter;
  src: url('/assets/fonts/Inter-Regular.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: Inter;
  src: url('/assets/fonts/Inter-ExtraBold.woff2') format('woff2');
  font-weight: 800;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: Inter;
  src: url('/assets/fonts/Inter-Bold.woff2') format('woff2');
  font-weight: bold;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: Inter;
  src: url('/assets/fonts/Inter-SemiBold.woff2') format('woff2');
  font-weight: 600;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: Inter;
  src: url('/assets/fonts/Inter-Medium.woff2') format('woff2');
  font-weight: 500;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: Inter;
  src: url('/assets/fonts/Inter-Thin.woff2') format('woff2');
  font-weight: 100;
  font-style: normal;
  font-display: swap;
}

@font-face {
  font-family: 'PT Mono';
  src: url('/assets/fonts/PT-Mono-Regular.woff2') format('woff2');
  font-weight: normal;
  font-style: normal;
}

@font-face {
  font-family: 'PT Mono';
  src: url('/assets/fonts/PT-Mono-Bold.woff2') format('woff2');
  font-weight: bold;
  font-style: normal;
}

:root {
  /* Font families for shadow DOM inheritance */
  --font-inter: 'Inter', ui-sans-serif, system-ui, sans-serif;
  --font-mono: 'PT Mono', ui-monospace, monospace;

  /* Font weights for shadow DOM inheritance */
  --font-weight-100: 100;
  --font-weight-200: 200;
  --font-weight-300: 300;
  --font-weight-400: 400;
  --font-weight-500: 500;
  --font-weight-600: 600;
  --font-weight-700: 700;
  --font-weight-800: 800;
  --font-weight-900: 900;
}
`

writeFileSync(fontsPath, fontsCss)
console.log('✓ Generated fonts-v4.css')

// 5. Generate shadows-v4.css with all box shadows from tailwind-config
const shadowsPath = join(generatedStylesDir, 'shadows-v4.css')
const shadowsV4Output = [
  '/* DO NOT MODIFY MANUALLY. This file is auto generated by scripts/generate-styles.js */',
  '/* Box Shadow variables for Tailwind v4 */',
  '',
  '/* :root section - for shadow DOM inheritance and external CSS usage */',
  ':root {',
]

for (const [name, value] of Object.entries(boxShadows)) {
  shadowsV4Output.push(`  --shadow-${name}: ${value};`)
}
shadowsV4Output.push('}', '')

shadowsV4Output.push(
  '/* @theme section - for Tailwind v4 shadow-* utilities */'
)
shadowsV4Output.push('@theme {')
for (const [name, value] of Object.entries(boxShadows)) {
  shadowsV4Output.push(`  --shadow-${name}: ${value};`)
}
shadowsV4Output.push('}', '')

const shadowsCss = shadowsV4Output.join('\n')
writeFileSync(shadowsPath, shadowsCss)
console.log('✓ Generated shadows-v4.css')

// 6. Read typography-v4.css to inline it
const typographyV4SourcePath = join(srcStylesDir, 'typography-v4.css')
const typographyV4Content = readFileSync(typographyV4SourcePath, 'utf-8')

// 6b. Read tippy-v4.css to inline it
const tippyV4SourcePath = join(srcStylesDir, 'tippy-v4.css')
const tippyV4Content = readFileSync(tippyV4SourcePath, 'utf-8')

// 6c. Read prose-overrides-v4.css to inline it
const proseOverridesV4SourcePath = join(srcStylesDir, 'prose-overrides-v4.css')
const proseOverridesV4Content = readFileSync(
  proseOverridesV4SourcePath,
  'utf-8'
)

// 7. Generate main-v4.css by inlining colors, fonts, shadows, typography, tippy, and prose overrides into template
const templatePath = join(srcStylesDir, 'main-v4.template.css')
const outputPath = join(generatedStylesDir, 'main-v4.css')

const mainV4Template = readFileSync(templatePath, 'utf-8')

// Remove import statements from template (colors, fonts, shadows, typography, tippy, prose overrides)
// and inline the actual content
const mainV4Css = mainV4Template
  .replace(/\/\* Import generated colors and fonts \*\/\n/g, '')
  .replace(/@import '\.\/colors-v4\.css';\n/g, '')
  .replace(/@import '\.\/fonts-v4\.css';\n/g, '')
  .replace(
    /\/\* Import typography classes for Tailwind v4 \(must come (before|after) tailwindcss for proper specificity\) \*\/\n@import '\.\/typography-v4\.css';\n/g,
    `/* Typography classes for Tailwind v4 - inlined and wrapped in @layer components */\n${typographyV4Content}\n`
  )
  .replace(
    /\/\* Import Tippy\.js tooltip styles for Tailwind v4 \*\/\n@import '\.\/tippy-v4\.css';\n/g,
    `/* Tippy.js tooltip styles for Tailwind v4 - inlined */\n${tippyV4Content}\n`
  )
  .replace(
    /\/\* Import prose customizations - must come after the plugin \*\/\n@import '\.\/prose-overrides-v4\.css';\n/g,
    `/* Prose customizations for Tailwind v4 Typography - inlined */\n${proseOverridesV4Content}\n`
  )

// Build the final CSS with everything inline
const finalCss = `/**
 * DO NOT MODIFY MANUALLY. This file is auto-generated.
 *
 * Source: main-v4.template.css + colors.css + colors-v4.css + fonts-v4.css + shadows-v4.css + typography-v4.css + tippy-v4.css + prose-overrides-v4.css
 * Generated by: scripts/generate-styles.js
 *
 * This file is imported by TailwindElement base class for Shadow DOM styles.
 * It includes BOTH :root (for external usage) and @theme (for Tailwind utilities).
 *
 * Users should add @source directive when importing this file to specify
 * which files Tailwind should scan for utility classes.
 */

${cssV3Output.join('\n')}

${cssOutput.join('\n')}

${fontsCss}

${shadowsCss}

${mainV4Css}
`

writeFileSync(outputPath, finalCss)
console.log('✓ Generated main-v4.css')

// 8. Copy typography-v4.css to generated folder (for reference)
const typographyV4DestPath = join(generatedStylesDir, 'typography-v4.css')
writeFileSync(typographyV4DestPath, typographyV4Content)
console.log('✓ Copied typography-v4.css')

// 9. Copy tippy-v4.css to generated folder (for reference)
const tippyV4DestPath = join(generatedStylesDir, 'tippy-v4.css')
writeFileSync(tippyV4DestPath, tippyV4Content)
console.log('✓ Copied tippy-v4.css')

// 10. Copy prose-overrides-v4.css to generated folder (for reference)
const proseOverridesV4DestPath = join(
  generatedStylesDir,
  'prose-overrides-v4.css'
)
writeFileSync(proseOverridesV4DestPath, proseOverridesV4Content)
console.log('✓ Copied prose-overrides-v4.css')

console.log('\n✓ All style files generated successfully')
console.log(`   - ${Object.keys(colorPalette).length} color groups`)
console.log(`   - ${Object.keys(boxShadows).length} box shadows`)
