on:
  push:
    branches:
      - main
  workflow_dispatch:

name: minimal release test
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug info
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Event number: ${{ github.event.number }}"
          git --no-pager log --oneline -5
          
      - name: Please release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node
          target-branch: main
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug outputs
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"
          echo "SHA: ${{ steps.release.outputs.sha }}"
          echo "PR: ${{ steps.release.outputs.pr }}"
          echo "Upload URL: ${{ steps.release.outputs.upload_url }}"
