on:
  push:
    branches:
      - main
      - patch/*
  pull_request:
    branches:
      - main
      - patch/*

env:
  PACKAGE_TYPE: node

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

name: github release (alternative)
jobs:
  release-please:
    outputs:
      tag_name: ${{ steps.version.outputs.tag_name }}
      sha: ${{ steps.version.outputs.sha }}
      release_created: ${{ steps.version.outputs.release_created }}
      pr_number: ${{ steps.version.outputs.pr_number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install release-please CLI
        if: ${{ github.event.number == '' }}
        run: npm install -g release-please

      - name: Run release-please via CLI
        if: ${{ github.event.number == '' }}
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run release-please with explicit retry logic
          ATTEMPT=1
          MAX_ATTEMPTS=3

          while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
            echo "Attempt $ATTEMPT of $MAX_ATTEMPTS"

            if release-please release-pr \
              --repo-url="${{ github.server_url }}/${{ github.repository }}" \
              --target-branch=main \
              --config-file=release-please-config.json \
              --manifest-file=.release-please-manifest.json; then

              echo "release_created=true" >> $GITHUB_OUTPUT
              echo "Release PR created successfully"
              break
            else
              if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
                echo "release_created=false" >> $GITHUB_OUTPUT
                echo "Failed after $MAX_ATTEMPTS attempts"
              else
                echo "Attempt $ATTEMPT failed, retrying in 30 seconds..."
                sleep 30
              fi
            fi

            ATTEMPT=$((ATTEMPT + 1))
          done

      - id: version
        name: Detect final version info
        run: |
          if [ "${{ steps.release.outputs.release_created }}" != "true" ]
          then
            SHA="${{ github.sha }}"
            RELEASE_CREATED="false"
            # For the extension we cannot use - but must use . for the PR number.
            DESCRIBE=$(git describe --tags --always)
            echo "describe: $DESCRIBE"
            OFFSET=$(echo $DESCRIBE | sed -n 's#.*-\([0-9]*\)-.*#\1#p')
            if [ -n "$OFFSET" ]
            then
              OFFSET=".${OFFSET}"
            fi
            if [ -z "${{ github.event.number }}" ]
            then
              TAG_NAME="v$(node -pe 'require("./.release-please-manifest.json")["."]')${OFFSET}"
            else
              TAG_NAME="v$(node -pe 'require("./.release-please-manifest.json")["."]').10000.${{ github.event.number }}"
            fi
            echo "PR: ${{ github.event.number }}"
          else
            SHA="${{ github.sha }}"
            RELEASE_CREATED="true"
            TAG_NAME="v$(node -pe 'require("./.release-please-manifest.json")["."]')"
          fi
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          echo "pr_number=${{ github.event.number }}" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "release_created=$RELEASE_CREATED" >> $GITHUB_OUTPUT
          echo "Tag: $TAG_NAME"
          echo "Sha: $SHA"
          echo "Release: $RELEASE_CREATED"

  artifacts-job:
    needs: release-please
    uses: ./.github/workflows/artifacts.yml
    secrets: inherit
    with:
      sha: ${{ needs.release-please.outputs.sha }}
      ref: ${{ github.ref }}
      tag_name: ${{ needs.release-please.outputs.tag_name }}
      release_created: ${{ needs.release-please.outputs.release_created }}
      pr_number: ${{ needs.release-please.outputs.pr_number }}
